version: '3'

services:
  postgres-database:
    image: bitnami/postgresql
    container_name: facilita-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=tests